name: Windows Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release

jobs:
  build:
    name: Build libks Windows
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          choco install nasm strawberryperl -y
          echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # https://learn.microsoft.com/en-us/visualstudio/releases/2019/history
      - name: Check available VS versions
        shell: cmd
        run: |
          where vswhere.exe
          vswhere.exe -all -prerelease -format json

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
          # https://github.com/microsoft/setup-msbuild?tab=readme-ov-file#specifying-specific-versions-of-visual-studio-optional
          # vs-version: "[16.11,16.12)"

      - name: Build All Configurations
        shell: cmd
        working-directory: win
        run: |
          CALL build.cmd

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libks-windows-builds
          path: win/out/*.zip
          if-no-files-found: error
          retention-days: 7
